{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" $ }}
          servicePort: {{ $.Values.service.externalPort }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .name }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
{{- end -}}
